version: '3'

services:
  publisher:
    build: ./src/publisher/
    env_file: .env
    depends_on:
      - storage
      - database
    networks:
      - backend

  tagger:
    build: ./src/tagger/
    env_file: .env
    networks:
      - backend

  uploader:
    build: ./src/uploader/
    env_file: .env
    depends_on:
      - storage
      - database
    networks:
      - backend

  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: "sansetto"
      POSTGRES_USER: "sansetto_user"
      POSTGRES_PASSWORD: "sansetto"
    ports:
      - "5432:5432"

  storage:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data:/data
    command: server /data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - uploader
      - tagger
    networks:
      - backend

networks:
  backend:
