version: '3'

services:
  panel:
    build: ./
    env_file: .env
    volumes:
      - ./instance:/app/instance
    ports:
      - "5000:5000"
    entrypoint: /app/entrypoint.sh

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    volumes:
      - ./data:/data
    command: server /data

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - panel

networks:
  default:
    external:
      name: bridge
