version: '3'

services:
  panel:
    build: ./
    env_file: .env
    volumes:
      - ./instance:/app/instance
    entrypoint: /app/entrypoint.sh
    depends_on:
      - minio
    networks:
      - backend

  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./data:/data
    command: server /data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - panel
    networks:
      - backend

networks:
  backend:
